baseURL = "https://samuelgomez.co/"
title = "Samuel G."
paginate = 8
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
env = "production"
title = "Samuel G."
description = "Our little corner on the internet"
keywords = [ "Blog", "Portfolio", "sagoez", "Scala", "Rust"]
author = "@sagoez"
images = [ "https://avatars.githubusercontent.com/u/39674930?v=4" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "icon.png"
  favicon16x16 = "icon.png"
  favicon32x32 = "icon.png"
  apple_touch_icon = "icon.png"
  safari_pinned_tab = "icon.png"

  [params.label]
  text = "Home"
  icon = "icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Hi there ðŸ‘‹"
  Content = "I'm Samuel, a software engineer and this is my little corner of the internet. I write about software development, technology, and other things that interest me."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/sagoez"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/sagoez/sagoez/edit/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "https://drive.google.com/file/d/1YsOB4vjHxFO4FupYuJhnjNRovAlSi0DZ/view?usp=sharing"
weight = 40

[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/sagoez"
weight = 50

[markup.highlight]
noClasses = false
